"""Initial schema

Revision ID: 17ef59a741f0
Revises: 
Create Date: 2026-09-18 13:59:18.885619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ef59a741f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('student_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('concept_mastery_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('concept_id', sa.String(), nullable=True),
    sa.Column('historical_mastery', sa.Float(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('misconceptions_observed', sa.JSON(), nullable=True),
    sa.Column('evidence_history', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_mastery_states_concept_id'), 'concept_mastery_states', ['concept_id'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('learning_plan', sa.JSON(), nullable=True),
    sa.Column('current_checkpoint_id', sa.String(), nullable=True),
    sa.Column('current_hint_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision_schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('concept_id', sa.String(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revision_schedules_concept_id'), 'revision_schedules', ['concept_id'], unique=False)
    op.create_table('mastery_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('concept_state_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('checkpoint_id', sa.String(), nullable=True),
    sa.Column('student_response', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('mastery_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_state_id'], ['concept_mastery_states.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mastery_attempts')
    op.drop_index(op.f('ix_revision_schedules_concept_id'), table_name='revision_schedules')
    op.drop_table('revision_schedules')
    op.drop_table('learning_sessions')
    op.drop_index(op.f('ix_concept_mastery_states_concept_id'), table_name='concept_mastery_states')
    op.drop_table('concept_mastery_states')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
